name: Node.js CI Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Archive Production Artifacts
        run: |
          mkdir -p build
          cp -r * build
        if: success()

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build
